In [ ]:
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split

TO DO: import load_wine from sklearn.datasets
 Then, create an instance __dataset__ by calling load_wine()

TO DO: Display dataset.keys() and the elements of dataset.

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


['class_0' 'class_1' 'class_2']


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


TO DO: Split dataset into train and test sets, and print the shape of X_train, y_train, X_test and y_test

X_train.shape =  (133, 13)
y_train.shape =  (133,)
X_test.shape =  (45, 13)
y_test.shape =  (45,)


TO DO: Build a classifier for the wine dataset using LogisicRegression, and print the accuracy on the training and test data.


train score =  0.9699248120300752
test score =  0.9555555555555556


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


TO DO: Save the weight matrix and bias vector of the LogisticRegression instance as W_lr and b_lr. Then, print them.

W_lr =  [[-6.90183749e-02  2.38838439e-01  1.35507349e-01 -3.23757639e-01
  -1.58243552e-02  1.73272770e-01  4.63287797e-01 -2.82546756e-02
   9.66605888e-02 -3.89779937e-02  1.87265758e-03  3.90888766e-01
   8.32988332e-03]
 [ 3.81189686e-01 -7.74891589e-01 -1.61892417e-01  1.57041175e-01
   3.15868256e-02  2.53401642e-01  4.05285805e-01  2.78706704e-02
   2.87958905e-01 -1.13109143e+00  2.17356447e-01  2.58113549e-01
  -8.17270164e-03]
 [-3.12171311e-01  5.36053150e-01  2.63850677e-02  1.66716464e-01
  -1.57624704e-02 -4.26674411e-01 -8.68573602e-01  3.84005123e-04
  -3.84619493e-01  1.17006943e+00 -2.19229105e-01 -6.49002315e-01
  -1.57181680e-04]]
b_lr =  [-0.03764298  0.08568735 -0.04804437]


TO DO: Build a classifier for the wine dataset using LinearSVC, and print the accuracy on the training and test data.

train score =  0.8345864661654135
test score =  0.8666666666666667


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


TO DO: Save the weight matrix and bias vector of the LinearSVC instance as W_svc and b_svc. Then, print them.

W_svc =  [[-3.04431731e-02 -4.70176051e-03 -2.23258339e-03 -9.51132679e-02
  -1.00380377e-02  5.87616869e-03  2.21786937e-02 -3.46972969e-03
   5.32694549e-03 -2.55390968e-02 -6.26646432e-04  1.25945364e-02
   5.03681548e-03]
 [ 4.39881601e-02 -8.95590213e-02 -6.63218274e-03  2.50774974e-02
   8.06976802e-03  5.15129442e-02  8.40907851e-02  6.55661874e-04
   4.51610809e-02 -1.81991195e-01  3.12879900e-02  7.94818910e-02
  -9.64532559e-04]
 [-3.66546319e-02  8.77130954e-02  2.24122655e-03  1.47673978e-02
  -6.54579140e-03 -7.04243074e-02 -1.30355257e-01  3.42072886e-03
  -5.31964761e-02  2.09138458e-01 -3.39554880e-02 -1.04978348e-01
  -1.95777357e-04]]
b_svc =  [-0.00378211  0.00846829 -0.00615907]


TO DO: Define a class __SimpleLinearClassifier__ composed of the following functions:

* __\_\_init\_\___(self, weight, bias) - takes a weight matrix and a bias vector as input and stores them in instance variables

* __predict(self, X)__ - takes an array of rank 2 as input, and returns the classification results as an array of rank 1

* __probability(self, X)__ - takes an array of rank 2 as input and returns the probabilities that each sample belongs to each class as an array of rank 2. (You need to implement the softmax function to convert logits into probabilities.)

* __score(self, X, y)__ - takes an input data (rank 2) and a target vector (rank 1) as input, and returns the accuracy as a scalar value.


The __SimpleLinearClassifier__ should work as the following examples.

In [ ]:
# Define SimpleLienarClassfier here.

TO DO: Create a SimpleLinearClassfier instance simple_lr using W_lr and b_lr. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LogisticRegression instance.)

train score =  0.9699248120300752
test score =  0.9555555555555556


TO DO: Display the results of simple_lr.predict(X_test) along with y_test.

y_hat =  [2 1 0 1 0 2 1 0 2 1 0 1 1 0 1 1 2 0 1 0 0 1 1 1 0 2 0 0 0 2 1 2 2 0 1 1 1
 1 1 0 0 1 2 0 0]
y_test =  [2 1 0 1 0 2 1 0 2 1 0 0 1 0 1 1 2 0 1 0 0 1 2 1 0 2 0 0 0 2 1 2 2 0 1 1 1
 1 1 0 0 1 2 0 0]


TO DO: Display the result of simple_lr.probability(X_test).
Then, check whether the sum of each row makes one.

prob =  [[1.48200456e-02 9.28649765e-03 9.75893457e-01]
 [8.91068465e-06 9.99984128e-01 6.96101500e-06]
 [9.83847281e-01 1.44912745e-02 1.66144417e-03]
 [9.98040267e-03 9.89929235e-01 9.03627342e-05]
 [9.99758755e-01 6.01176928e-06 2.35233424e-04]
 [6.74254766e-03 6.05841079e-03 9.87199042e-01]
 [8.11777340e-02 8.55399847e-01 6.34224190e-02]
 [9.99997753e-01 8.15269040e-09 2.23878964e-06]
 [2.89802307e-04 7.89238979e-05 9.99631274e-01]
 [1.15622806e-03 9.94139982e-01 4.70378979e-03]
 [9.99681701e-01 7.60003760e-05 2.42298572e-04]
 [1.50288613e-01 8.41316520e-01 8.39486679e-03]
 [8.15163901e-05 9.99896756e-01 2.17271802e-05]
 [9.99676153e-01 2.72277242e-04 5.15700225e-05]
 [5.19705540e-03 9.94655621e-01 1.47323769e-04]
 [4.00827074e-04 9.99191493e-01 4.07680147e-04]
 [8.76760694e-05 6.73491982e-02 9.32563126e-01]
 [9.05786687e-01 8.75293087e-02 6.68400445e-03]
 [9.74180831e-05 9.99603415e-01 2.99167274e-04]
 [9.99762975e-01 6.84972741e-07 2.36340192e-04]
 [9.99836246e-01 4.23938761e-05 

TO DO: Print the accuracy on the training and test data.

train score =  0.9699248120300752
test score =  0.9555555555555556


TO DO: Create a SimpleLinearClassfier instance simple_svc using W_svc and b_svc. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LinearSVC instance.)

TO DO: Display the results of simple_svc.predict(X_test) along with y_test.

y_hat =  [1 1 0 1 0 1 1 0 2 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 0 1 0 0 0 2 1 2 2 0 1 1 1
 1 1 0 0 1 2 0 0]
y_test =  [2 1 0 1 0 2 1 0 2 1 0 0 1 0 1 1 2 0 1 0 0 1 2 1 0 2 0 0 0 2 1 2 2 0 1 1 1
 1 1 0 0 1 2 0 0]


TO DO: Display the result of simple_svc.probability(X_test).
Then, check whether the sum of each row makes one.

prob =  [[0.27901498 0.41143696 0.30954806]
 [0.02587174 0.92406631 0.05006195]
 [0.59077911 0.33899802 0.07022287]
 [0.20172206 0.75591492 0.04236301]
 [0.96329595 0.02565883 0.01104522]
 [0.2257629  0.39341763 0.38081947]
 [0.20843821 0.64861848 0.1429433 ]
 [0.99340665 0.00397647 0.00261688]
 [0.14067056 0.29063541 0.56869404]
 [0.10196374 0.7607518  0.13728446]
 [0.95035456 0.03660345 0.01304199]
 [0.25634312 0.65412531 0.08953157]
 [0.04384445 0.88630706 0.06984849]
 [0.88158737 0.09648571 0.02192693]
 [0.15077007 0.77515043 0.0740795 ]
 [0.0817573  0.81962044 0.09862225]
 [0.04200625 0.60656587 0.35142788]
 [0.58882209 0.34146026 0.06971764]
 [0.03642169 0.8666048  0.09697351]
 [0.98162058 0.01145611 0.0069233 ]
 [0.94579479 0.04035944 0.01384577]
 [0.05093217 0.84951134 0.09955649]
 [0.21572233 0.64168667 0.14259101]
 [0.22303939 0.73874982 0.03821079]
 [0.4812966  0.43563029 0.0830731 ]
 [0.14724154 0.52523636 0.3275221 ]
 [0.78409637 0.16986264 0.04604099]
 [0.82686271 0.14177

TO DO: Print the accuracy on the training and test data.

train score =  0.8345864661654135
test score =  0.8666666666666667
