In [134]:
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split

TO DO: import load_wine from sklearn.datasets
 Then, create an instance __dataset__ by calling load_wine()

In [135]:
from sklearn.datasets import load_wine
dataset = load_wine()

TO DO: Display dataset.keys() and the elements of dataset.

In [136]:
print(dataset.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [137]:
print(dataset.get('DESCR'))

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [138]:
print(dataset.get('feature_names'))

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [139]:
print(dataset.get('data'))

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [140]:
print(dataset.get('target_names'))

['class_0' 'class_1' 'class_2']


In [141]:
print(dataset.get('target'))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


TO DO: Split dataset into train and test sets, and print the shape of X_train, y_train, X_test and y_test

In [142]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(dataset.get('data'), dataset.get('target'))

print("X_train.shape =", X_train.shape)
print("y_train.shape =", y_train.shape)
print("X_test.shape =", X_test.shape)
print("y_test.shape =", y_test.shape)

X_train.shape = (133, 13)
y_train.shape = (133,)
X_test.shape = (45, 13)
y_test.shape = (45,)


TO DO: Build a classifier for the wine dataset using LogisicRegression, and print the accuracy on the training and test data.


In [143]:
from sklearn.linear_model import LogisticRegression
logi_reg = LogisticRegression().fit(X_train,y_train)

print("train score =", logi_reg.score(X_train, y_train))
print("test score =", logi_reg.score(X_test, y_test))

train score = 0.9849624060150376
test score = 0.9333333333333333


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


TO DO: Save the weight matrix and bias vector of the LogisticRegression instance as W_lr and b_lr. Then, print them.

In [144]:
W_lr = logi_reg.coef_
b_lr = logi_reg.intercept_

print("W_lr =", W_lr)
print("b_lr =", b_lr)

W_lr = [[-8.11548697e-02  1.79510253e-01  1.01611752e-01 -3.82991595e-01
   1.72317176e-02  1.65917417e-01  4.37205342e-01 -2.74547311e-02
   1.09415992e-01 -1.08185414e-01 -4.62952931e-03  2.88479032e-01
   7.02665148e-03]
 [ 2.85353254e-01 -6.64335209e-01 -1.11749188e-01  7.44801702e-02
   5.60633917e-02  2.23690658e-01  2.85877516e-01  9.04484898e-03
   1.83306382e-01 -1.25428320e+00  1.88796652e-01  3.34187434e-01
  -7.01037671e-03]
 [-2.04198385e-01  4.84824956e-01  1.01374354e-02  3.08511424e-01
  -7.32951093e-02 -3.89608075e-01 -7.23082858e-01  1.84098821e-02
  -2.92722375e-01  1.36246861e+00 -1.84167123e-01 -6.22666465e-01
  -1.62747760e-05]]
b_lr = [-0.03084798  0.06902057 -0.03817259]


TO DO: Build a classifier for the wine dataset using LinearSVC, and print the accuracy on the training and test data.

In [130]:
from sklearn.svm import LinearSVC
linear_svm = LinearSVC().fit(X_train,y_train)

print("train score =", linear_svm.score(X_train, y_train))
print("test score =", linear_svm.score(X_test, y_test))

train score = 0.7142857142857143
test score = 0.7777777777777778


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


TO DO: Save the weight matrix and bias vector of the LinearSVC instance as W_svc and b_svc. Then, print them.

In [131]:
W_svc = linear_svm.coef_
b_svc = linear_svm.intercept_

print("W_svc =", W_svc)
print("b_svc =", b_svc)


W_svc = [[-3.44382672e-02 -4.42061663e-03 -2.12949964e-03 -1.17375219e-01
  -2.76102440e-05  9.21616707e-03  2.79096984e-02 -4.09301644e-03
   6.10936372e-03 -2.83191442e-02 -7.75116918e-04  1.35062227e-02
   2.90302325e-03]
 [ 3.89555602e-02 -6.62967370e-02 -4.45135923e-03  4.11321069e-02
   4.38556074e-03  4.54266373e-02  7.75121043e-02  1.38132704e-03
   4.38941008e-02 -1.96797026e-01  3.06781996e-02  8.06369609e-02
  -5.81277033e-04]
 [-3.88999157e-02  6.86798065e-02 -7.20090644e-04  7.35254803e-03
  -3.47167852e-03 -6.69529335e-02 -1.27452677e-01  2.67027717e-03
  -5.28445025e-02  2.16445089e-01 -3.29193975e-02 -1.09528974e-01
  -2.53913225e-04]]
b_svc = [-0.0044991   0.00854809 -0.00626464]


TO DO: Define a class __SimpleLinearClassifier__ composed of the following functions:

* __\_\_init\_\___(self, weight, bias) - takes a weight matrix and a bias vector as input and stores them in instance variables

* __predict(self, X)__ - takes an array of rank 2 as input, and returns the classification results as an array of rank 1

* __probability(self, X)__ - takes an array of rank 2 as input and returns the probabilities that each sample belongs to each class as an array of rank 2. (You need to implement the softmax function to convert logits into probabilities.)

* __score(self, X, y)__ - takes an input data (rank 2) and a target vector (rank 1) as input, and returns the accuracy as a scalar value.


The __SimpleLinearClassifier__ should work as the following examples.

In [132]:
# Define SimpleLienarClassfier here.
class SimpleLinearClassifier:
    def __init__(self, weight, bias):
        self.weight = weight
        self.bias = bias      
      
    def predict(self,X):

        # X is an array of rank 2
        reg = np.matmul(X, np.transpose(self.weight)) + self.bias
        # result size is sample * class
        sample_num, class_num = reg.shape
        prediction = np.amax(reg,1)
        for i in range(sample_num):
            for j in range(class_num):
                if(prediction[i] == reg[i][j]):
                    prediction[i] = int(j)
                    break
        
        return prediction.astype(int)

    def softmax(self, in_vector):
        e = np.exp(in_vector - np.max(in_vector))
        return e / e.sum()


    def probability(self,X):
        # X is an array of rank 2
        reg = np.matmul(X, np.transpose(self.weight)) + self.bias
        sample_num, class_num = reg.shape
        prob_m = np.zeros((sample_num, class_num))
        for i in range(sample_num):
            prob_m[i] = self.softmax(reg[i,:])


        return prob_m

    
    def score(self,X, y):
        # X is an array of rank 2
        # y is an vector of rank 1
        y_hat = self.predict(X)
        score_vector =  y_hat == y
        return np.mean(score_vector)

TO DO: Create a SimpleLinearClassfier instance simple_lr using W_lr and b_lr. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LogisticRegression instance.)

In [110]:
simple_lr = SimpleLinearClassifier(W_lr, b_lr)

print("train score =",simple_lr.score(X_train, y_train)) 
print("test score =",simple_lr.score(X_test, y_test))  


train score = 0.9774436090225563
test score = 0.9333333333333333


TO DO: Display the results of simple_lr.predict(X_test) along with y_test.

In [111]:
print("y_hat =",simple_lr.predict(X_test))
print("y_test =",y_test)    

y_hat = [1 2 1 1 2 1 1 0 1 1 1 0 1 1 2 2 1 0 0 1 1 2 0 0 0 1 1 0 0 1 1 0 0 2 1 0 0
 1 2 2 0 0 1 1 0]
y_test = [1 2 1 1 2 1 1 1 1 1 1 0 1 1 2 1 1 0 0 1 1 2 0 0 0 1 1 0 0 1 1 0 0 2 1 0 0
 1 1 2 0 0 1 1 0]


TO DO: Display the result of simple_lr.probability(X_test).
Then, check whether the sum of each row makes one.

In [113]:
print("prob =",simple_lr.probability(X_test))
print("The sum of rows =",np.sum(simple_lr.probability(X_test), 1))

prob = [[4.24484450e-02 8.34534203e-01 1.23017352e-01]
 [3.67329448e-05 2.84783393e-09 9.99963264e-01]
 [2.34474010e-02 9.75059498e-01 1.49310112e-03]
 [4.60605677e-01 4.71635895e-01 6.77584285e-02]
 [2.12396458e-02 2.35416125e-02 9.55218742e-01]
 [3.62565032e-01 6.32461846e-01 4.97312148e-03]
 [9.52985045e-03 9.90253325e-01 2.16824134e-04]
 [5.21468129e-01 3.60988168e-01 1.17543702e-01]
 [1.41808526e-02 9.84854057e-01 9.65090315e-04]
 [2.36358506e-04 9.99609501e-01 1.54140250e-04]
 [2.20071786e-04 9.99612615e-01 1.67313494e-04]
 [9.65881141e-01 2.85391684e-02 5.57969073e-03]
 [7.87286715e-02 8.12554773e-01 1.08716556e-01]
 [5.36355383e-02 5.23480112e-01 4.22884349e-01]
 [6.12033488e-06 3.22998887e-07 9.99993557e-01]
 [8.52348955e-03 1.93074011e-02 9.72169109e-01]
 [9.65042756e-04 9.97953458e-01 1.08149935e-03]
 [9.99977212e-01 2.04529767e-06 2.07429070e-05]
 [9.99850204e-01 2.73767858e-07 1.49522558e-04]
 [4.02245815e-01 4.61891562e-01 1.35862623e-01]
 [4.20829365e-01 5.67201255e-01 1

TO DO: Print the accuracy on the training and test data.

In [114]:
print("train score =",simple_lr.score(X_train, y_train)) 
print("test score =",simple_lr.score(X_test, y_test))

train score = 0.9774436090225563
test score = 0.9333333333333333


TO DO: Create a SimpleLinearClassfier instance simple_svc using W_svc and b_svc. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LinearSVC instance.)

In [115]:
simple_svc = SimpleLinearClassifier(W_svc, b_svc)

print("train score =",simple_svc.score(X_train, y_train)) 
print("test score =",simple_svc.score(X_test, y_test))


train score = 0.6766917293233082
test score = 0.5777777777777777


TO DO: Display the results of simple_svc.predict(X_test) along with y_test.

In [116]:
print("y_hat =",simple_svc.predict(X_test))
print("y_test =",y_test) 

y_hat = [1 2 1 2 2 1 1 2 1 1 1 2 1 1 2 2 1 2 2 2 1 2 2 0 2 1 1 2 2 1 1 2 2 2 1 2 1
 1 2 2 2 2 1 1 2]
y_test = [1 2 1 1 2 1 1 1 1 1 1 0 1 1 2 1 1 0 0 1 1 2 0 0 0 1 1 0 0 1 1 0 0 2 1 0 0
 1 1 2 0 0 1 1 0]


TO DO: Display the result of simple_svc.probability(X_test).
Then, check whether the sum of each row makes one.

In [117]:
print("prob =",simple_svc.probability(X_test))
print("The sum of rows =",np.sum(simple_lr.probability(X_test), 1))

prob = [[0.06005397 0.58752551 0.35242052]
 [0.02257687 0.02201739 0.95540574]
 [0.06018101 0.69696333 0.24285566]
 [0.10549635 0.4432325  0.45127114]
 [0.04743636 0.30379666 0.64876697]
 [0.11224047 0.5453806  0.34237893]
 [0.04922453 0.63758142 0.31319406]
 [0.11761616 0.3011393  0.58124454]
 [0.06752412 0.70029357 0.23218231]
 [0.02313445 0.83805545 0.1388101 ]
 [0.01962165 0.81865808 0.16172027]
 [0.18398757 0.32501406 0.49099837]
 [0.06503471 0.51090547 0.42405982]
 [0.05864212 0.513795   0.42756288]
 [0.01301229 0.07014154 0.91684617]
 [0.05221053 0.3619611  0.58582838]
 [0.03360652 0.68439169 0.28200179]
 [0.40473328 0.04543286 0.54983386]
 [0.33909129 0.0327203  0.62818841]
 [0.11852445 0.4005016  0.48097396]
 [0.12556953 0.47826211 0.39616835]
 [0.01751666 0.05360757 0.92887577]
 [0.15756281 0.40333424 0.43910295]
 [0.51326567 0.01772366 0.46901067]
 [0.18029188 0.15418107 0.66552705]
 [0.0743431  0.61577904 0.30987786]
 [0.0515652  0.57680881 0.37162599]
 [0.2254379  0.157456

TO DO: Print the accuracy on the training and test data.

In [118]:
print("train score =",simple_svc.score(X_train, y_train)) 
print("test score =",simple_svc.score(X_test, y_test))

train score = 0.6766917293233082
test score = 0.5777777777777777
